[package]
name = "eggtunnel-cli"
description = "Eggtunnel command line application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
eggtunnel = { path = "../eggtunnel", features = ["client", "server", "tls", "mtls", "quic", "websocket", "outbound-proxy"] }
clap.workspace = true
serde.workspace = true
toml.workspace = true
tokio = { workspace = true, features = ["signal"] }

[[bin]]
name = "eggtunnel"
path = "src/main.rs"
doc = false
