[package]
name = "eggtunnel-cli"
description = "Eggtunnel command line application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
eggtunnel = { path = "../eggtunnel", features = ["client", "server", "tls"] }

