[package]
name = "eggtunnel"
description = "Embeddable Eggtunnel reverse-session library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["client", "tls"]
client = ["dep:tokio", "dep:tokio-util", "dep:eggress-core", "dep:eggress-transport-tls", "dep:eggress-relay", "dep:getrandom", "dep:rustls", "tls"]
server = ["dep:tokio", "dep:tokio-util", "dep:eggress-core", "dep:eggress-transport-tls", "dep:eggress-relay", "dep:rustls", "tls"]
tls = ["dep:eggress-transport-tls"]
quic = ["client", "server", "dep:eggress-transport-quic"]
websocket = ["client", "server", "dep:eggress-protocol-websocket", "dep:tokio-tungstenite"]
outbound-proxy = ["client", "dep:eggress-outbound"]
mtls = ["tls", "dep:tokio-rustls", "dep:rustls-pemfile", "dep:webpki-roots", "dep:sha2"]

[dependencies]
eggtunnel-proto = { path = "../eggtunnel-proto", version = "0.1.0" }
tokio = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
eggress-core = { workspace = true, optional = true }
eggress-relay = { workspace = true, optional = true }
eggress-transport-tls = { workspace = true, optional = true }
eggress-transport-quic = { workspace = true, optional = true }
eggress-protocol-websocket = { workspace = true, optional = true }
eggress-outbound = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true, optional = true }
subtle.workspace = true
zeroize.workspace = true
getrandom = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
tokio-rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }
webpki-roots = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
thiserror.workspace = true

[dev-dependencies]
rcgen = "0.13"
eggress-transport-quic = { workspace = true, features = ["insecure-quic"] }
